export const color = {
    white: '#FFFFFF',
    black: '#000000',
    primary: {
        main: '#262758',
        light: '#4042B1',
    },
    error: '#F2706A',
};

// export const color = {
//     primary: '#262758',
//     white: '#FFFFFF',
//     grey: '#858585',
//     error: '#F2706A',
//     davy_grey: '#555555',
//     night_rider: '#2C2C2C',
//     whisper: '#ECECEC',
//     alice_blue: '#ECF4F9',
//     solitude: '#F4F5F7',
//     white_smoke: '#F2F2F2',
//     cold_purple: '#A0A4DF',
//     chambray: '#3C498A',
//     nobel: '#B7B7B7',
//     cornflower_blue: '#6C63FF',
//     silver_chalice: '#9F9F9F',
//     flamingo: '#F04D46',
//     vanilla_ice: '#F2D8D9',
//     perano: '#B0B6EF',
//     pale_prim: '#FEFEBA',
//     dark_grey: '#A9A9A9',
//     snow: '#FAFAFA',
//     banana_mania: '#FFE9AC',
//     light_blue: '#EDEEFF',
//     blue_zodiac: '#45485B',
// };
